main:
  steps:
    - run_pipelines:
        parallel:
          branches:
            - opa_properties:
                steps:
                  - extract_properties:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-opa-properties
                        auth:
                          type: OIDC
                      result: extract_props_result
                  - prepare_properties:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-opa-properties
                        auth:
                          type: OIDC
                      result: prepare_props_result
                  - load_properties:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-opa-properties
                        auth:
                          type: OIDC
                      result: load_props_result

            - opa_assessments:
                steps:
                  - extract_assessments:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-opa-assessments
                        auth:
                          type: OIDC
                      result: extract_assess_result
                  - prepare_assessments:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-opa-assessments
                        auth:
                          type: OIDC
                      result: prepare_assess_result
                  - load_assessments:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-opa-assessments
                        auth:
                          type: OIDC
                      result: load_assess_result

            - pwd_parcels:
                steps:
                  - extract_parcels:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-pwd-parcels
                        auth:
                          type: OIDC
                      result: extract_parcels_result
                  - prepare_parcels:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-pwd-parcels
                        auth:
                          type: OIDC
                      result: prepare_parcels_result
                  - load_parcels:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-pwd-parcels
                        auth:
                          type: OIDC
                      result: load_parcels_result

            - external_data:
                steps:
                  - extract_crime:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-crime
                        auth:
                          type: OIDC
                      result: extract_crime_result
                  - prepare_crime:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-crime
                        auth:
                          type: OIDC
                      result: prepare_crime_result
                  - load_crime:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-crime
                        auth:
                          type: OIDC
                      result: load_crime_result
                  - extract_recreation:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-recreation
                        auth:
                          type: OIDC
                      result: extract_rec_result
                  - prepare_recreation:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-recreation
                        auth:
                          type: OIDC
                      result: prepare_rec_result
                  - load_recreation:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-recreation
                        auth:
                          type: OIDC
                      result: load_rec_result
                  - extract_transit:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-transit
                        auth:
                          type: OIDC
                      result: extract_transit_result
                  - prepare_transit:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-transit
                        auth:
                          type: OIDC
                      result: prepare_transit_result
                  - load_transit:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-transit
                        auth:
                          type: OIDC
                      result: load_transit_result
                  - extract_hospitals:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-hospitals
                        auth:
                          type: OIDC
                      result: extract_hospitals_result
                  - prepare_hospitals:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-hospitals
                        auth:
                          type: OIDC
                      result: prepare_hospitals_result
                  - load_hospitals:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-hospitals
                        auth:
                          type: OIDC
                      result: load_hospitals_result
                  - extract_schools:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-schools
                        auth:
                          type: OIDC
                      result: extract_schools_result
                  - prepare_schools:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-schools
                        auth:
                          type: OIDC
                      result: prepare_schools_result
                  - load_schools:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-schools
                        auth:
                          type: OIDC
                      result: load_schools_result
                  - extract_census_tracts:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/extract-census-tracts
                        auth:
                          type: OIDC
                      result: extract_census_result
                  - prepare_census_tracts:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/prepare-census-tracts
                        auth:
                          type: OIDC
                      result: prepare_census_result
                  - load_census_tracts:
                      call: http.post
                      args:
                        url: https://us-central1-musa5090s26-team2.cloudfunctions.net/load-census-tracts
                        auth:
                          type: OIDC
                      result: load_census_result

    - generate_residential_market_value_geojson:
        call: http.post
        args:
          url: https://us-central1-musa5090s26-team2.cloudfunctions.net/generate-residential-market-value-geojson
          auth:
            type: OIDC
        result: residential_geojson_result

    - success:
        return: "All pipelines completed successfully"
